tap 'caskroom/cask'

brew 'git'
brew 'mtr'
brew 'npm'
brew 'awscli'
brew 'awslogs'
brew 'aws-elasticbeanstalk'
brew 'aws-as'
brew 'aws-mon'
brew 'antigen'
brew 'bash-completion'
brew 'ansible'
brew 'nmap'
brew 'rsync'
brew 'ipcalc'
brew 'htop'
brew 'wget'
brew 'tmux'
brew 'screen'
brew 'diff-so-fancy'
brew 'git-extras'
brew 'httpie'

cask 'brackets'
cask 'atom'
cask 'iterm2'
cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'google-earth'
cask 'google-photos-backup'
cask 'gimp'
cask 'spectacle'
cask 'sequel-pro'
cask 'vlc'
cask 'slack'
cask 'virtualbox'
cask 'virtualbox-extension-pack'
cask 'little-snitch'
cask 'caffeine'
cask 'slate'
cask 'telegram'

# now using docker for mac
#cask 'docker'

